name: Mergebot
author: Matthew Mukerjee <mukerjee@nefeli.io>
description: Automatically git rebase a PR and merge it when passing branch protections.
inputs:
  github_token:
    description: Token for the GitHub API.
    required: true
  jira_user_token:
    description: Combination of user:token for the JIRA API.
  jira_server:
    description: JIRA API server.
runs:
  using: docker
  image: docker://ghcr.io/nefeli/mergebot:latest
branding:
  icon: git-pull-request
  color: yellow
